Manual shared-memory management (#391)
This PR adds `test_explicit_shared_gemm` to validate GEMM kernels with
explicit shared memory allocation and manual memory transfers.

The key issue was that when users manually allocate shared memory and
write to it (e.g.,` tkw.write(global_data, allocate)`), the compiler's
Dead Code Elimination (DCE) incorrectly removed these writes because
read nodes had no _write_dependency linking them to the writes showing
up as `[num_users = 0]` in the IR . Fixed by adding
`fix_manual_allocate_dependencies()` to set write dependencies for
user-created allocates after the `promote_placeholders` pass.

Another issue fixed is the NoneType error (below) when using shared
memory. Fixed by adding infer_type() method, and setting the
fx_node.type to a memory type.
```
    def infer_type(self, *args):
        from ..wave.utils.general_utils import infer_dim
    
>       address_space = self.memory_type.address_space
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       AttributeError: 'NoneType' object has no attribute 'address_space'
```

---------

Signed-off-by: Sanket Pandit <sanket.pandit@amd.com>